<?php

namespace ccxt;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import

class bingx extends Exchange {

    public function describe() {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'bingx',
            'name' => 'BingX',
            'countries' => array( 'EU' ),
            'rateLimit' => 100,
            'version' => 'v1',
            'pro' => true,
            'has' => array(
                'CORS' => true,
                'spot' => true,
                'margin' => null,
                'swap' => false,
                'future' => false,
                'option' => false,
                'cancelOrder' => true,
                'createDepositAddress' => false,
                'createOrder' => true,
                'fetchBalance' => true,
                'fetchDepositAddress' => false,
                'fetchDepositAddresses' => false,
                'fetchFundingHistory' => false,
                'fetchFundingRate' => false,
                'fetchFundingRateHistory' => false,
                'fetchFundingRates' => false,
                'fetchIndexOHLCV' => false,
                'fetchMarkOHLCV' => false,
                'fetchOHLCV' => true,
                'fetchOpenInterestHistory' => false,
                'fetchOpenOrders' => true,
                'fetchOrderBook' => true,
                'fetchPositionMode' => true,
                'fetchPositions' => true,
                'fetchPremiumIndexOHLCV' => false,
                'fetchTicker' => true,
                'fetchTrades' => true,
                'fetchTradingFee' => false,
                'fetchTradingFees' => false,
                'setMarginMode' => true,
                'setPositionMode' => true,
                'transfer' => false,
            ),
            'urls' => array(
                'logo' => '',
                'api' => array(
                    'swap' => 'https://api-swap-rest.bingx.com/api',
                    'swap2' => 'https://open-api.bingx.com',
                ),
                'test' => array(
                ),
                'www' => 'https://bingx.com/',
                'doc' => array(
                    'https://bingx-api.github.io/docs',
                ),
                'fees' => array(
                    'https://support.bingx.com/hc/en-001/articles/360027240173',
                ),
                'referral' => '',
            ),
            'api' => array(
                'swap' => array(
                    'v1' => array(
                        'public' => array(
                            'get' => array(
                                'market/getAllContracts' => 1,
                                'market/getLatestPrice' => 1,
                                'market/getMarketDepth' => 1,
                                'market/getMarketTrades' => 1,
                                'market/getLatestFunding' => 1,
                                'market/getHistoryFunding' => 1,
                                'market/getLatestKline' => 1,
                                'market/getHistoryKlines' => 1,
                                'market/getOpenPositions' => 1,
                                'market/getTicker' => 1,
                            ),
                            'post' => array(
                                'common/server/time' => 1,
                            ),
                        ),
                        'private' => array(
                            'post' => array(
                                'user/getBalance' => 1,
                                'user/getPositions' => 1,
                                'user/trade' => 1,
                                'user/oneClickClosePosition' => 1,
                                'user/oneClickCloseAllPositions' => 1,
                                'user/cancelOrder' => 1,
                                'user/batchCancelOrders' => 1,
                                'user/cancelAll' => 1,
                                'user/pendingOrders' => 1,
                                'user/pendingStopOrders' => 1,
                                'user/queryOrderStatus' => 1,
                                'user/setMarginMode' => 1,
                                'user/setLeverage' => 1,
                                'user/forceOrders' => 1,
                                'user/historyOrders' => 1,
                                'user/auth/userDataStream' => 1,
                            ),
                            'put' => array(
                                'user/auth/userDataStream' => 1,
                            ),
                        ),
                    ),
                ),
                'swap2' => array(
                    'openApi' => array(
                        'public' => array(
                            'get' => array(
                                'swap/v2/quote/klines' => 1,
                            ),
                        ),
                        'private' => array(
                            'get' => array(
                                'swap/v2/trade/openOrders' => 1,
                                'swap/v2/trade/leverage' => 1,
                                'swap/v2/trade/marginType' => 1,
                                'swap/v1/positionSide/dual' => 1,
                            ),
                            'put' => array(
                                'user/auth/userDataStream' => 1,
                            ),
                            'post' => array(
                                'user/auth/userDataStream' => 1,
                                'swap/v2/trade/order' => 1,
                                'swap/v2/trade/leverage' => 1,
                                'swap/v2/trade/marginType' => 1,
                                'swap/v1/positionSide/dual' => 1,
                            ),
                            'delete' => array(
                                'swap/v2/trade/order' => 1,
                                'swap/v2/trade/allOpenOrders' => 1,
                            ),
                        ),
                    ),
                ),
            ),
            'markets' => array(
                'BTC/EUR' => array( 'id' => 'eur', 'symbol' => 'BTC/EUR', 'base' => 'BTC', 'quote' => 'EUR', 'baseId' => 'btc', 'quoteId' => 'eur', 'type' => 'spot', 'spot' => true ),
            ),
            'fees' => array(
                'trading' => array(
                    'tierBased' => true,
                    'percentage' => true,
                    'maker' => $this->parse_number('0.0002'),
                    'taker' => $this->parse_number('0.0004'),
                ),
            ),
            'precisionMode' => TICK_SIZE,
            'requiredCredentials' => array(
                'apiKey' => true,
                'secret' => true,
            ),
            'timeframes' => array(
                '1m' => '1',
                '3m' => '3',
                '5m' => '5',
                '15m' => '15',
                '30m' => '30',
                '1h' => '60',
                '2h' => '120',
                '4h' => '240',
                '6h' => '360',
                '12h' => '720',
                '1d' => '1D',
                '1w' => '1W',
                '1M' => '1M',
            ),
            'options' => array(
                'listenKeyRefreshRate' => 1200000, // 20 mins
                'defaultType' => 'swap',
                'defaultSubType' => 'linear',
            ),
            'orderTypes' => array(
                'market' => 'MARKET',
                'limit' => 'LIMIT',
                'stop' => 'STOP',
                'stoplimit' => 'STOP',
                'marketiftouched' => 'TAKE_PROFIT_MARKET',
                'limitiftouched' => 'TAKE_PROFIT',
            ),
            'reverseOrderTypes' => array(
                'market' => 'Market',
                'limit' => 'Limit',
                'stop_market' => 'Stop',
                'stoplimit' => 'StopLimit',
                'take_profit_market' => 'Stop',
                'take_profit' => 'StopLimit',
                'limit_maker' => 'Limit',
            ),
            'triggerTypes' => array(
                'Mark' => 'MARK_PRICE',
                'Last' => 'CONTRACT_PRICE',
            ),
            'timeInForces' => array(
                'GTC' => 'GTC',
                'PO' => 'GTX',
                'IOC' => 'IOC',
                'FOK' => 'FOK',
            ),
        ));
    }

    public function switch_isolated($symbol, $isIsolated, $buyLeverage, $sellLeverage, $params = array ()) {
        if ($isIsolated) {
            $this->set_margin_mode('ISOLATED', $symbol, $params);
        } else {
            $this->set_margin_mode('CROSSED', $symbol, $params);
        }
    }

    public function set_margin_mode($marginMode, $symbol = null, $params = array ()) {
        /**
         * set margin mode to 'cross' or 'isolated'
         * @param {string} $marginMode 'cross' or 'isolated'
         * @param {string} $symbol unified $market $symbol
         * @param {array} $params extra parameters specific to the bitget api endpoint
         * @return {array} response from the exchange
         */
        $marginMode = strtolower($marginMode);
        if ($marginMode === 'cross') {
            $marginMode = 'CROSSED';
        }
        if ($marginMode === 'isolated') {
            $marginMode = 'ISOLATED';
        }
        if ($symbol === null) {
            throw new ArgumentsRequired($this->id . ' setMarginMode() requires a $symbol argument');
        }
        if (($marginMode !== 'ISOLATED') && ($marginMode !== 'CROSSED')) {
            throw new ArgumentsRequired($this->id . ' (' . $marginMode . ') ' . ' setMarginMode() $marginMode must be "isolated" or "crossed"');
        }
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'symbol' => $market['id'],
            'marginType' => $marginMode,
        );
        $params = $this->omit($params, array( 'leverage', 'buyLeverage', 'sellLeverage' ));
        try {
            return $this->swap2OpenApiPrivatePostSwapV2TradeMarginType (array_merge($request, $params));
        } catch (Exception $e) {
            if ($e instanceof ExchangeError) {
                if (string) (mb_strpos($e, '80001') !== false) {
                    throw new ExchangeError($this->id . ' ' . $this->json(array( 'code' => 80001, 'msg' => 'Cannot switch Margin Type for $market with open positions or orders.' )));
                }
            }
            throw $e;
        }
    }

    public function set_position_mode($hedged, $symbol = null, $params = array ()) {
        $this->load_markets();
        $mode = null;
        if ($hedged) {
            $mode = 'true';
        } else {
            $mode = 'false';
        }
        $request = array(
            'dualSidePosition' => $mode,
        );
        // if ($symbol === null) {
        //     $request['coin'] = 'USDT';
        // } else {
        //     $market = $this->market($symbol);
        //     // TEALSTREET
        //     $request['category'] = $market['linear'] ? 'linear' : 'inverse';
        //     // TEALSTREET
        //     $request['symbol'] = $market['id'];
        // }
        //
        //     {
        //         "ret_code" => 0,
        //         "ret_msg" => "ok",
        //         "ext_code" => "",
        //         "result" => null,
        //         "ext_info" => null,
        //         "time_now" => "1577477968.175013",
        //         "rate_limit_status" => 74,
        //         "rate_limit_reset_ms" => 1577477968183,
        //         "rate_limit" => 75
        //     }
        //
        return $this->swap2OpenApiPrivatePostSwapV1PositionSideDual (array_merge($request, $params));
    }

    public function set_leverage($leverage, $symbol = null, $params = array ()) {
        /**
         * set the level of $leverage for a $market
         * @param {float} $leverage the rate of $leverage
         * @param {string} $symbol unified $market $symbol
         * @param {array} $params extra parameters specific to the bitget api endpoint
         * @return {array} response from the exchange
         */
        if ($symbol === null) {
            throw new ArgumentsRequired($this->id . ' setLeverage() requires a $symbol argument');
        }
        $buyLeverage = $this->safe_number($params, 'buyLeverage', $leverage);
        $sellLeverage = $this->safe_number($params, 'sellLeverage', $leverage);
        $this->load_markets();
        $market = $this->market($symbol);
        $params = $this->omit($params, array( 'marginMode', 'positionMode' ));
        $promises = array();
        $request = array(
            'symbol' => $market['id'],
        );
        if ($buyLeverage !== null) {
            $request['leverage'] = $this->parse_to_int($buyLeverage);
            $request['side'] = 'LONG';
            $promises[] = $this->swap2OpenApiPrivatePostSwapV2TradeLeverage (array_merge($request, $params));
        }
        if ($sellLeverage !== null) {
            $request['leverage'] = $this->parse_to_int($sellLeverage);
            $request['side'] = 'SHORT';
            $promises[] = $this->swap2OpenApiPrivatePostSwapV2TradeLeverage (array_merge($request, $params));
        }
        $promises = $promises;
        if (strlen($promises) === 1) {
            return $promises[0];
        } else {
            return $promises;
        }
    }

    public function fetch_account_configuration($symbol, $params = array ()) {
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'symbol' => $market['id'],
        );
        $leverageResponse = $this->swap2OpenApiPrivateGetSwapV2TradeLeverage (array_merge($request, $params));
        $leverageData = $this->safe_value($leverageResponse, 'data');
        $marginTypeResponse = $this->swap2OpenApiPrivateGetSwapV2TradeMarginType (array_merge($request, $params));
        $marginTypeData = $this->safe_value($marginTypeResponse, 'data');
        $positionModeResponse = $this->swap2OpenApiPrivateGetSwapV1PositionSideDual (array_merge($request, $params));
        $positionModeData = $this->safe_value($positionModeResponse, 'data');
        return $this->parse_account_configuration($leverageData, $marginTypeData, $positionModeData, $market);
    }

    public function parse_account_configuration($leverageData, $marginTypeData, $positionModeData, $market) {
        // {
        //     "marginCoin":"USDT",
        //   "locked":0,
        //   "available":13168.86110692,
        //   "crossMaxAvailable":13168.86110692,
        //   "fixedMaxAvailable":13168.86110692,
        //   "maxTransferOut":13168.86110692,
        //   "equity":13178.86110692,
        //   "usdtEquity":13178.861106922,
        //   "btcEquity":0.344746495477,
        //   "crossRiskRate":0,
        //   "crossMarginLeverage":20,
        //   "fixedLongLeverage":20,
        //   "fixedShortLeverage":20,
        //   "marginMode":"crossed",
        //   "holdMode":"double_hold"
        // }
        // $marginMode = $this->safe_string(data, 'marginMode');
        // $isIsolated = ($marginMode === 'fixed');
        // $leverage = $this->safe_float(data, 'crossMarginLeverage');
        // $buyLeverage = $this->safe_float(data, 'fixedLongLeverage');
        // $sellLeverage = $this->safe_float(data, 'fixedShortLeverage');
        // $marginCoin = $this->safe_string(data, 'marginCoin');
        // $holdMode = $this->safe_string(data, 'holdMode');
        // $positionMode = 'hedged';
        // if ($holdMode === 'single_hold') {
        //     $positionMode = 'oneway';
        //     if ($isIsolated) {
        //         $leverage = $buyLeverage;
        //     }
        // }
        // $accountConfig = array(
        //     'info' => data,
        //     'markets' => array(),
        //     'positionMode' => $positionMode,
        //     'marginMode' => $isIsolated ? 'isolated' : 'cross',
        // );
        // $leverageConfigs = $accountConfig['markets'];
        // $leverageConfigs[$market['symbol']] = array(
        //     'marginMode' => $isIsolated ? 'isolated' : 'cross',
        //     'isIsolated' => $isIsolated,
        //     'leverage' => $leverage,
        //     'buyLeverage' => $buyLeverage,
        //     'sellLeverage' => $sellLeverage,
        //     'marginCoin' => $marginCoin,
        //     'positionMode' => $positionMode,
        // );
        $buyLeverage = $this->safe_float($leverageData, 'longLeverage');
        $sellLeverage = $this->safe_float($leverageData, 'shortLeverage');
        $maxBuyLeverage = $this->safe_float($leverageData, 'maxLongLeverage');
        $maxSellLeverage = $this->safe_float($leverageData, 'maxShortLeverage');
        $marginType = $this->safe_string($marginTypeData, 'marginType');
        $isHedged = $this->safe_string($positionModeData, 'dualSidePosition');
        $positionMode = 'hedged';
        if ($isHedged === 'false') {
            $positionMode = 'oneway';
        }
        $isIsolated = ($marginType === 'ISOLATED');
        $accountConfig = array(
            'marginMode' => $isIsolated ? 'isolated' : 'cross',
            'positionMode' => $positionMode,
            'markets' => array(),
        );
        $leverageConfigs = $accountConfig['markets'];
        $leverageConfigs[$market['symbol']] = array(
            'buyLeverage' => $buyLeverage,
            'sellLeverage' => $sellLeverage,
            'maxBuyLeverage' => $maxBuyLeverage,
            'maxSellLeverage' => $maxSellLeverage,
            'positionMode' => $positionMode,
        );
        return $accountConfig;
    }

    public function fetch_contract_markets($params = array ()) {
        $response = $this->swapV1PublicGetMarketGetAllContracts ($params);
        //
        //     {
        //         "code":0,
        //         "msg":"Success",
        //         "data":{
        //             "contracts":array(
        //                 {
        //                     "contractId":"100",
        //                     "symbol":"BTC-USDT",
        //                     "name":"BTC",
        //                     "size":"0.0001",
        //                     "currency":"USDT",
        //                     "asset":"BTC",
        //                     "pricePrecision":2,
        //                     "volumePrecision":4,
        //                     "feeRate":0.0005,
        //                     "tradeMinLimit":1,
        //                     "maxLongLeverage":100,
        //                     "maxShortLeverage":100,
        //                     "status":1
        //                 }
        //             )
        //         }
        //     }
        //
        $result = array();
        $data = $this->safe_value($response, 'data', array());
        $contracts = $this->safe_value($data, 'contracts', array());
        for ($i = 0; $i < count($contracts); $i++) {
            $market = $contracts[$i];
            // should we use contract id id?
            // $contractId = $this->safe_string($market, 'contractId');
            $marketId = $this->safe_string($market, 'symbol');
            $parts = explode('-', $marketId);
            $baseId = $this->safe_string($parts, 0);
            $quoteId = $this->safe_string($parts, 1);
            $settleId = $this->safe_string($market, 'currency');
            $base = $this->safe_currency_code($baseId);
            $quote = $this->safe_currency_code($quoteId);
            $settle = $this->safe_currency_code($settleId);
            $symbol = $base . '/' . $quote . ':' . $settle;
            $status = $this->safe_number($market, 'status');
            // $contractSize = $this->safe_number($market, 'size', 1);
            $contractSize = 1;
            $result[] = array(
                'id' => $marketId,
                'symbol' => $symbol,
                'base' => $base,
                'quote' => $quote,
                'settle' => $settle,
                'baseId' => $baseId,
                'quoteId' => $quoteId,
                'settleId' => $settleId,
                'type' => 'swap',
                'spot' => false,
                'margin' => true,
                'swap' => true,
                'future' => false,
                'option' => false,
                'active' => $status === 1,
                'contract' => true,
                'linear' => true,
                'inverse' => null,
                'contractSize' => $contractSize,
                'expiry' => null,
                'expiryDatetime' => null,
                'strike' => null,
                'optionType' => null,
                'precision' => array(
                    'amount' => $this->parse_number($this->parse_precision($this->safe_string($market, 'volumePrecision'))),
                    'price' => $this->parse_number($this->parse_precision($this->safe_string($market, 'pricePrecision'))),
                ),
                'limits' => array(
                    'leverage' => array(
                        'min' => null,
                        'max' => $this->safe_number($market, 'maxLongLeverage'),
                    ),
                    'amount' => array(
                        'min' => $this->safe_number($market, 'size'),
                        'max' => null,
                    ),
                    'price' => array(
                        'min' => null,
                        'max' => null,
                    ),
                    'cost' => array(
                        'min' => null,
                        'max' => null,
                    ),
                ),
                'info' => $market,
            );
        }
        return $result;
    }

    public function fetch_markets($params = array ()) {
        /**
         * retrieves data on all markets for bingx
         * @param {array} $params extra parameters specific to the exchange api endpoint
         * @return {[array]} an array of objects representing market data
         */
        $contract = $this->fetch_contract_markets($params);
        return $contract;
    }

    public function parse_balance($response) {
        $result = array( 'info' => $response );
        $data = $this->safe_value($response, 'data', array());
        $dataAccount = $this->safe_value($data, 'account', array());
        $currencies = is_array($this->currencies) ? array_keys($this->currencies) : array();
        for ($i = 0; $i < count($currencies); $i++) {
            $code = $currencies[$i];
            $account = $this->account();
            if ($this->safe_string($dataAccount, 'currency', '') === $code) {
                $account['free'] = $this->safe_string($dataAccount, 'availableMargin');
                $account['used'] = $this->safe_string($dataAccount, 'usedMargin');
                $account['total'] = $this->safe_string($dataAccount, 'balance');
            }
            $result[$code] = $account;
        }
        return $this->safe_balance($result);
    }

    public function fetch_balance($params = array ()) {
        /**
         * query for balance and get the amount of funds available for trading or funds locked in orders
         * @param {array} $params extra parameters specific to the bingx api endpoint
         * @return {array} a ~@link https://docs.ccxt.com/en/latest/manual.html?#balance-structure balance structure~
         */
        // $this->load_markets();
        $response = $this->swapV1PrivatePostUserGetBalance ($params);
        return $this->parse_balance($response);
    }

    public function fetch_order_book($symbol, $limit = null, $params = array ()) {
        /**
         * fetches information on open orders with bid (buy) and ask (sell) prices, volumes and other data
         * @param {string} $symbol unified $symbol of the $market to fetch the order book for
         * @param {int|null} $limit the maximum amount of order book entries to return
         * @param {array} $params extra parameters specific to the paymium api endpoint
         * @return {array} A dictionary of ~@link https://docs.ccxt.com/#/?id=order-book-structure order book structures~ indexed by $market symbols
         */
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'currency' => $market['id'],
        );
        $response = $this->publicGetDataCurrencyDepth (array_merge($request, $params));
        return $this->parse_order_book($response, $market['symbol'], null, 'bids', 'asks', 'price', 'amount');
    }

    public function parse_ticker($ticker, $market = null) {
        //
        // {
        //   "symbol" => "BTC-USDT",
        //   "priceChange" => "10.00",
        //   "priceChangePercent" => "10",
        //   "lastPrice" => "5738.23",
        //   "lastVolume" => "31.21",
        //   "highPrice" => "5938.23",
        //   "lowPrice" => "5238.23",
        //   "volume" => "23211231.13",
        //   "dayVolume" => "213124412412.47",
        //   "openPrice" => "5828.32"
        // }
        //
        $symbol = $this->safe_symbol(null, $market);
        $timestamp = $this->milliseconds();
        $baseVolume = $this->safe_string($ticker, 'volume');
        $last = $this->safe_string($ticker, 'lastPrice');
        if ($last === '-') {
            $last = null;
        }
        $high = $this->safe_string($ticker, 'highPrice');
        if ($high === '-') {
            $high = null;
        }
        $low = $this->safe_string($ticker, 'lowPrice');
        if ($low === '-') {
            $low = null;
        }
        $open = $this->safe_string($ticker, 'openPrice');
        if ($open === '-') {
            $open = null;
        }
        $percentage = $this->safe_string($ticker, 'priceChangePercent');
        if ($percentage === '-') {
            $percentage = null;
        }
        return $this->safe_ticker(array(
            'symbol' => $symbol,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'high' => $high,
            'low' => $low,
            'bid' => $last,
            'bidVolume' => null,
            'ask' => $last,
            'askVolume' => null,
            'open' => $open,
            'close' => $last,
            'last' => $last,
            'mark' => $last,
            'previousClose' => null,
            'change' => null,
            'percentage' => $percentage,
            'average' => null,
            'baseVolume' => $baseVolume,
            'info' => $ticker,
        ), $market);
    }

    public function fetch_ticker($symbol, $params = array ()) {
        /**
         * fetches a price $ticker, a statistical calculation with the information calculated over the past 24 hours for a specific $market
         * @param {string} $symbol unified $symbol of the $market to fetch the $ticker for
         * @param {array} $params extra parameters specific to the paymium api endpoint
         * @return {array} a ~@link https://docs.ccxt.com/#/?id=$ticker-structure $ticker structure~
         */
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'symbol' => $market['id'],
        );
        $response = $this->swapV1PublicGetMarketGetTicker (array_merge($request, $params));
        //
        // {
        //   "symbol" => "BTC-USDT",
        //   "priceChange" => "10.00",
        //   "priceChangePercent" => "10",
        //   "lastPrice" => "5738.23",
        //   "lastVolume" => "31.21",
        //   "highPrice" => "5938.23",
        //   "lowPrice" => "5238.23",
        //   "volume" => "23211231.13",
        //   "dayVolume" => "213124412412.47",
        //   "openPrice" => "5828.32"
        // }
        //
        $data = $this->safe_value($response, 'data');
        $tickers = $this->safe_value($data, 'tickers');
        $ticker = $this->safe_value($tickers, 0);
        return $this->parse_ticker($ticker, $market);
    }

    public function parse_trade($trade, $market = null) {
        $timestamp = $this->safe_timestamp($trade, 'created_at_int');
        $id = $this->safe_string($trade, 'uuid');
        $market = $this->safe_market(null, $market);
        $side = $this->safe_string($trade, 'side');
        $price = $this->safe_string($trade, 'price');
        $amountField = 'traded_' . strtolower($market['base']);
        $amount = $this->safe_string($trade, $amountField);
        return $this->safe_trade(array(
            'info' => $trade,
            'id' => $id,
            'order' => null,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'symbol' => $market['symbol'],
            'type' => null,
            'side' => $side,
            'takerOrMaker' => null,
            'price' => $price,
            'amount' => $amount,
            'cost' => null,
            'fee' => null,
        ), $market);
    }

    public function fetch_trades($symbol, $since = null, $limit = null, $params = array ()) {
        return array();
        // /**
        //
        //
        //  * get the list of most recent trades for a particular $symbol
        //  * @param {string} $symbol unified $symbol of the $market to fetch trades for
        //  * @param {int|null} $since timestamp in ms of the earliest trade to fetch
        //  * @param {int|null} $limit the maximum amount of trades to fetch
        //  * @param {array} $params extra parameters specific to the paymium api endpoint
        //  * @return {[array]} a list of ~@link https://docs.ccxt.com/en/latest/manual.html?#public-trades trade structures~
        //  */
        // $this->load_markets();
        // $market = $this->market($symbol);
        // $request = array(
        //     'currency' => $market['id'],
        // );
        // $response = $this->publicGetDataCurrencyTrades (array_merge($request, $params));
        // return $this->parse_trades($response, $market, $since, $limit);
    }

    public function fetch_my_trades($symbol = null, $since = null, $limit = null, $params = array ()) {
        // {
        //     "code" => 0,
        //     "data" => {
        //     "orders" => array(
        //         array(
        //             "action" => "Open",
        //             "avgFilledPrice" => 31333.37,
        //             "commission" => -0.0009,
        //             "entrustPrice" => 31331.25,
        //             "entrustTm" => "2021-01-05T09:15:02Z",
        //             "entrustVolume" => 0.0001,
        //             "filledVolume" => 0.0001,
        //             "orderId" => "996273190",
        //             "orderStatus" => "Filled",
        //             "profit" => 0,
        //             "side" => "Bid",
        //             "symbol" => "BTC-USDT",
        //             "tradeType" => "Market",
        //             "updateTm" => "2021-01-05T09:15:15Z"
        //         }
        //     )
        // ),
        //     "message" => ""
        // }
        $this->load_markets();
        $market = null;
        $request = array();
        if ($symbol !== null) {
            $market = $this->market($symbol);
            $request['symbol'] = $market['id'];
        }
        $request['lastOrderId'] = 0;
        $request['length'] = 100;
        $request['timestamp'] = $this->milliseconds() - 0;
        $response = $this->swapV1PrivatePostUserHistoryOrders (array_merge($request, $params));
        $data = $this->safe_value($response, 'data');
        $trades = $this->safe_value($data, 'orders');
        return $this->parse_my_trades($trades, $market, $since, $limit);
    }

    public function parse_my_trades($trades, $market = null, $since = null, $limit = null, $params = array ()) {
        $result = array();
        for ($i = 0; $i < count($trades); $i++) {
            $filled = $this->safe_number($trades[$i], 'filledVolume', 0);
            if ($filled <= 0) {
                continue;
            }
            $action = $this->safe_string($trades[$i], 'action');
            if ($action === 'Close') {
                continue;
            }
            $trade = array_merge($this->parse_my_trade($trades[$i], $market), $params);
            $result[] = $trade;
        }
        $result = $this->sort_by($result, 'timestamp');
        $symbol = ($market !== null) ? $market['symbol'] : null;
        $tail = ($since === null);
        return $this->filter_by_symbol_since_limit($result, $symbol, $since, $limit, $tail);
    }

    public function parse_my_trade($trade, $market = null) {
        // {
        //     'orderId' => '1657690927243935744',
        //     'side' => 'Ask',
        //     'action' => 'Close',
        //     'tradeType' => 'Limit',
        //     'entrustVolume' => '0.0003',
        //     'entrustPrice' => '26337.6',
        //     'filledVolume' => '0',
        //     'avgFilledPrice' => '0',
        //     'entrustTm' => '2023-05-14T10:14:50Z',
        //     'symbol' => 'BTC-USDT',
        //     'profit' => '0',
        //     'commission' => '0',
        //     'updateTm' => '2023-05-14T10:14:50Z',
        //     'orderStatus' => 'Cancelled'
        // }
        $marketId = $this->safe_string($trade, 'symbol');
        $market = $this->safe_market($marketId);
        $symbol = $market['symbol'];
        $rawSide = $this->safe_string($trade, 'side');
        $id = $this->safe_string($trade, 'orderId');
        $action = $this->safe_string($trade, 'action');
        $type = $this->safe_string($trade, 'tradeType');
        $ePrice = $this->safe_string($trade, 'entrustPrice');
        $filled = $this->safe_string($trade, 'filledVolume');
        $avgFilledPrice = $this->safe_string($trade, 'avgFilledPrice');
        $entrustTm = $this->safe_string($trade, 'entrustTm');
        $timestamp = $this->parse_date($entrustTm);
        $profit = $this->safe_string($trade, 'profit');
        $commission = $this->safe_string($trade, 'commission');
        $status = $this->safe_string($trade, 'orderStatus');
        $isClose = false;
        if ($action === 'Close') {
            $isClose = true;
        }
        $side = null;
        if ($rawSide === 'Bid') {
            $side = 'buy';
        } else {
            $side = 'sell';
        }
        $takerOrMaker = null;
        $tradeType = $this->safe_string($trade, 'tradeType');
        if ($tradeType === 'Market') {
            $takerOrMaker = 'taker';
        } else {
            $takerOrMaker = 'maker';
        }
        $cost = 0.00045;
        if ($takerOrMaker === 'taker') {
            $cost = 0.00075;
        }
        return $this->safe_order(array(
            'info' => $trade,
            'id' => $id,
            'symbol' => $symbol,
            'side' => $side,
            'type' => $type,
            'filled' => $filled,
            'amount' => $filled,
            'average' => $avgFilledPrice,
            'takerOrMaker' => $takerOrMaker,
            'price' => $ePrice,
            'profit' => $profit,
            'fees' => $commission,
            'status' => $status,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'isClose' => $isClose,
            'fee' => array(
                'currency' => $market['quote'],
                'cost' => $cost,
            ),
        ));
    }

    public function create_order($symbol, $type, $side, $amount, $price = null, $params = array ()) {
        /**
         * create a trade $order
         * @param {string} $symbol unified $symbol of the $market to create an $order in
         * @param {string} $type 'market' or 'limit'
         * @param {string} $side 'buy' or 'sell'
         * @param {float} $amount how much of currency you want to trade in units of base currency
         * @param {float|null} $price the $price at which the $order is to be fullfilled, in units of the quote currency, ignored in $market orders
         * @param {array} $params extra parameters specific to the paymium api endpoint
         * @return {array} an ~@link https://docs.ccxt.com/#/?id=$order-structure $order structure~
         */
        // quick $order:
        //
        // BTC/USDT:USDT
        // limit
        // buy
        // 4.0
        // 29116.0
        // array('positionMode' => 'unknown', 'timeInForce' => 'PO', 'reduceOnly' => False)
        //
        // limit $order:
        //
        // BTC/USDT:USDT
        // limit
        // buy
        // 4.0
        // 28520.0
        // array('positionMode' => 'unknown', 'timeInForce' => 'PO', 'reduceOnly' => False)
        //
        // no post = 'timeInForce' => 'GTC',
        //
        // SL
        //
        // BTC/USDT:USDT
        // stop
        // sell
        // 20.0
        // None
        // array('positionMode' => 'unknown', 'stopPrice' => 27663.0, 'timeInForce' => 'GTC', 'trigger' => 'Last', 'close' => True, 'basePrice' => 29024.0)
        //
        // TP
        //
        // BTC/USDT:USDT
        // stop
        // sell
        // 20.0
        // None
        // array('positionMode' => 'unknown', 'stopPrice' => 30150.0, 'timeInForce' => 'GTC', 'trigger' => 'Last', 'close' => True, 'basePrice' => 29024.0)
        //
        // LIMIT TP
        //
        // BTC/USDT:USDT
        // stopLimit
        // sell
        // 4.0
        // 33000.0
        // array('positionMode' => 'unknown', 'stopPrice' => 32000.0, 'timeInForce' => 'GTC', 'trigger' => 'Last', 'close' => True, 'basePrice' => 29024.0)
        $this->load_markets();
        $market = $this->market($symbol);
        //
        $triggerPrice = $this->safe_value_2($params, 'stopPrice', 'triggerPrice');
        $triggerType = $this->safe_string_lower_2($params, 'trigger', 'workingType');
        // $isTriggerOrder = $triggerPrice !== null;
        $isStopLossOrder = null;
        $isTakeProfitOrder = null;
        $reduceOnly = $this->safe_value_2($params, 'close', 'reduceOnly', false);
        $basePrice = $this->safe_value($params, 'basePrice');
        $positionSide = null;
        if (!$reduceOnly) {
            if ($side === 'buy') {
                $positionSide = 'LONG';
            } else {
                $positionSide = 'SHORT';
            }
        } else {
            if ($side === 'buy') {
                $positionSide = 'SHORT';
            } else {
                $positionSide = 'LONG';
            }
        }
        if ($triggerPrice !== null && $basePrice !== null) {
            // triggerOrder is NOT stopOrder
            // $type = 'market';
            if ($reduceOnly) {
                if ($side === 'buy') {
                    if ($triggerPrice > $basePrice) {
                        $isStopLossOrder = true;
                    } else {
                        $isTakeProfitOrder = true;
                    }
                } else {
                    if ($triggerPrice < $basePrice) {
                        $isStopLossOrder = true;
                    } else {
                        $isTakeProfitOrder = true;
                    }
                }
            } else {
                if ($side === 'buy') {
                    if ($triggerPrice < $basePrice) {
                        $isStopLossOrder = true;
                    } else {
                        $isTakeProfitOrder = true;
                    }
                } else {
                    if ($triggerPrice > $basePrice) {
                        $isStopLossOrder = true;
                    } else {
                        $isTakeProfitOrder = true;
                    }
                }
            }
        }
        //
        $convertedType = strtoupper($type);
        if ($type === 'stop') {
            if ($isTakeProfitOrder) {
                $convertedType = 'TRIGGER_MARKET';
            } elseif ($isStopLossOrder) {
                $convertedType = 'TRIGGER_MARKET';
            } else {
                throw new ArgumentsRequired('unknown $order direction for TP/SL');
            }
        }
        if ($type === 'stopLimit') {
            $convertedType = 'TRIGGER_LIMIT';
        }
        $convertedSide = strtoupper($side);
        $request = array(
            'symbol' => $market['id'],
            'type' => $convertedType,
            'side' => $convertedSide,
            'quantity' => $amount,
            'positionSide' => $positionSide,
        );
        if ($type === 'stop' || $type === 'stopLimit') {
            $triggerBy = 'MARK_PRICE';
            if ($triggerType === 'index') {
                $triggerBy = 'INDEX_PRICE';
            } elseif ($triggerType === 'last') {
                $triggerBy = 'CONTRACT_PRICE';
            }
            $request['workingType'] = $triggerBy;
        }
        if ($triggerPrice !== null) {
            $request['stopPrice'] = $this->price_to_precision($symbol, $triggerPrice);
            if ($convertedType === 'TRIGGER_LIMIT') {
                $request['price'] = $this->price_to_precision($symbol, $price);
            }
        } elseif ($triggerPrice === null && $convertedType === 'TRIGGER_LIMIT') {
            $request['price'] = $basePrice;
            $request['stopPrice'] = $basePrice;
        } elseif (($type === 'limit' || $type === 'stopLimit') && ($triggerPrice === null)) {
            $request['price'] = $this->price_to_precision($symbol, $price);
        }
        $isMarketOrder = $type === 'market';
        $exchangeSpecificParam = $this->safe_string_2($params, 'force', 'timeInForce');
        $postOnly = $this->is_post_only($isMarketOrder, $exchangeSpecificParam === 'PO', $params);
        if ($postOnly) {
            $request['timeInForce'] = 'PostOnly';
        }
        // $response = $this->swap2OpenApiPrivatePostSwapV2TradeOrder (array_merge($request, $params));
        $response = $this->swap2OpenApiPrivatePostSwapV2TradeOrder ($request);
        // var_dump('response', $response);
        $data = $this->safe_value($response, 'data');
        $order = $this->safe_value($data, 'order');
        // $parsedOrder = $this->parse_order($order, $market);
        // $patchedOrder = array_merge($parsedOrder, $params);
        // $patchedOrder = array_merge($patchedOrder, array(
        //     'price' => $price,
        //     'amount' => $amount,
        //     'side' => $side,
        //     'type' => $type,
        // ));
        return $this->parse_order($order, $market);
    }

    public function cancel_all_orders($symbol = null, $params = array ()) {
        /**
         * cancel all open orders in a $market
         * @see https://github.com/phemex/phemex-api-docs/blob/master/Public-Hedged-Perpetual-API.md#cancelall
         * @param {string} $symbol unified $market $symbol of the $market to cancel orders in
         * @param {array} $params extra parameters specific to the phemex api endpoint
         * @return {[array]} a list of ~@link https://docs.ccxt.com/#/?id=order-structure order structures~
         */
        if ($symbol === null) {
            throw new ArgumentsRequired($this->id . ' cancelAllOrders() requires a $symbol argument');
        }
        $this->load_markets();
        if ($symbol === null) {
            throw new ArgumentsRequired($this->id . ' cancelOrder() requires a $symbol argument');
        }
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'symbol' => $market['id'],
        );
        $response = $this->swap2OpenApiPrivateDeleteSwapV2TradeAllOpenOrders ($request);
        return $response;
    }

    public function cancel_order($id, $symbol = null, $params = array ()) {
        /**
         * cancels an open order
         * @param {string} $id order $id
         * @param {string} $symbol unified $symbol of the $market the order was made in
         * @param {array} $params extra parameters specific to the bitget api endpoint
         * @return {array} An {@link https://docs.ccxt.com/en/latest/manual.html#order-structure order structure}
         */
        if ($symbol === null) {
            throw new ArgumentsRequired($this->id . ' cancelOrder() requires a $symbol argument');
        }
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'symbol' => $market['id'],
            'orderId' => $id,
        );
        $response = $this->swap2OpenApiPrivateDeleteSwapV2TradeOrder ($request);
        return $this->parse_order($response, $market);
    }

    public function fetch_positions($symbols = null, $params = array ()) {
        /**
         * fetch all open $positions
         * @param {[string]|null} $symbols list of unified market $symbols
         * @param {array} $params extra parameters specific to the bybit api endpoint
         * @return {[array]} a list of ~@link https://docs.ccxt.com/#/?id=position-structure position structure~
         */
        $response = $this->swapV1PrivatePostUserGetPositions ();
        $data = $this->safe_value($response, 'data', array());
        $positions = $this->safe_value($data, 'positions', array());
        $result = array();
        for ($i = 0; $i < count($positions); $i++) {
            $result[] = $this->parse_position($positions[$i]);
        }
        return $result;
    }

    public function parse_position($position, $market = null) {
        //
        //
        // {
        //     "positionId" => "1650546544279240704",
        //     "symbol" => "BTC-USDT",
        //     "currency" => "",
        //     "volume" => 0.001,
        //     "availableVolume" => 0.001,
        //     "positionSide" => "short",
        //     "marginMode" => "cross",
        //     "avgPrice" => 27124.5,
        //     "liquidatedPrice" => 0.0,
        //     "margin" => 2.9386,
        //     "leverage" => 5.0,
        //     "pnlRate" => -45.83,
        //     "unrealisedPNL" => -2.4863,
        //     "realisedPNL" => 0.0126
        // }
        //
        $marketId = $this->safe_string($position, 'symbol');
        $market = $this->safe_market($marketId, $market);
        $timestamp = $this->safe_integer($position, 'cTime');
        $marginMode = $this->safe_string_lower($position, 'marginMode');
        $hedged = true;
        $side = $this->safe_string_lower($position, 'positionSide');
        $contracts = $this->safe_float($position, 'volume');
        $liquidation = $this->safe_number($position, 'liquidatedPrice');
        if ($side === 'short') {
            $contracts = -1 * $contracts;
        }
        if ($liquidation === 0) {
            $liquidation = null;
        }
        $initialMargin = $this->safe_number($position, 'margin');
        return array(
            'info' => $position,
            'id' => $market['symbol'] . ':' . $side,
            'symbol' => $market['symbol'],
            'notional' => null,
            'marginMode' => $marginMode,
            'liquidationPrice' => $liquidation,
            'entryPrice' => $this->safe_number($position, 'avgPrice'),
            'unrealizedPnl' => $this->safe_number_2($position, 'unrealisedPNL', 'unrealizedPL'),
            'realizedPnl' => $this->safe_number_2($position, 'realisedPNL', 'realizedPL'),
            'percentage' => null,
            'contracts' => $contracts,
            'contractSize' => $this->safe_number($market, 'contractSize'),
            'side' => $side,
            'hedged' => $hedged,
            'timestamp' => $timestamp,
            'markPrice' => $this->safe_number($position, 'markPrice'),
            'datetime' => $this->iso8601($timestamp),
            'maintenanceMargin' => null,
            'maintenanceMarginPercentage' => null,
            'collateral' => $this->safe_number($position, 'margin'),
            'initialMargin' => $initialMargin,
            'initialMarginPercentage' => null,
            'leverage' => $this->safe_number($position, 'leverage'),
            'marginRatio' => null,
        );
    }

    public function fetch_ohlcv($symbol, $timeframe = '1m', $since = null, $limit = null, $params = array ()) {
        /**
         * fetches historical candlestick data containing the open, high, low, and close price, and the volume of a $market
         * @see https://bybit-exchange.github.io/docs/v5/market/kline
         * @see https://bybit-exchange.github.io/docs/v5/market/mark-kline
         * @see https://bybit-exchange.github.io/docs/v5/market/index-kline
         * @see https://bybit-exchange.github.io/docs/v5/market/preimum-index-kline
         * @param {string} $symbol unified $symbol of the $market to fetch OHLCV data for
         * @param {string} $timeframe the length of time each candle represents
         * @param {int|null} $since timestamp in ms of the earliest candle to fetch
         * @param {int|null} $limit the maximum amount of candles to fetch
         * @param {array} $params extra parameters specific to the bybit api endpoint
         * @return {[[int]]} A list of candles ordered, open, high, low, close, volume
         */
        $this->check_required_symbol('fetchOHLCV', $symbol);
        $this->load_markets();
        $market = $this->market($symbol);
        $request = array(
            'symbol' => $market['id'],
        );
        if ($limit === null) {
            $limit = 200; // default is 340 when requested with `$since`
        }
        if ($since !== null) {
            $request['startTime'] = $since;
        }
        $klineType = $this->safe_string($this->timeframes, $timeframe, $timeframe);
        $request['interval'] = $timeframe;
        if ($limit !== null) {
            // $request['limit'] = $limit; // max 1000, default 1000
            if ($klineType === '1') {
                $request['endTime'] = $since . $limit * 60 * 1000;
            } elseif ($klineType === '3') {
                $request['endTime'] = $since . $limit * 3 * 60 * 1000;
            } elseif ($klineType === '5') {
                $request['endTime'] = $since . $limit * 5 * 60 * 1000;
            } elseif ($klineType === '15') {
                $request['endTime'] = $since . $limit * 15 * 60 * 1000;
            } elseif ($klineType === '30') {
                $request['endTime'] = $since . $limit * 30 * 60 * 1000;
            } elseif ($klineType === '60') {
                $request['endTime'] = $since . $limit * 60 * 60 * 1000;
            } elseif ($klineType === '120') {
                $request['endTime'] = $since . $limit * 120 * 60 * 1000;
            } elseif ($klineType === '240') {
                $request['endTime'] = $since . $limit * 240 * 60 * 1000;
            } elseif ($klineType === '360') {
                $request['endTime'] = $since . $limit * 360 * 60 * 1000;
            } elseif ($klineType === '720') {
                $request['endTime'] = $since . $limit * 720 * 60 * 1000;
            } elseif ($klineType === '1D') {
                $request['endTime'] = $since . $limit * 24 * 60 * 60 * 1000;
            } elseif ($klineType === '1W') {
                $request['endTime'] = $since . $limit * 7 * 24 * 60 * 60 * 1000;
            } elseif ($klineType === '1M') {
                $request['endTime'] = $since . $limit * 30 * 24 * 60 * 60 * 1000;
            } else {
                $request['endTime'] = $since . $limit * 60 * 1000;
            }
        }
        // var_dump ('===============');
        // var_dump ('fetchOHLCV', $symbol, $timeframe, $since, $limit, $params, $klineType);
        // var_dump ('now', +new Date (), new Date ());
        // var_dump ('startTs', +new Date ($request['startTime']), new Date ($request['startTime']));
        // var_dump ('endTs', +new Date ($request['endTime']), new Date ($request['endTime']));
        $response = $this->swap2OpenApiPublicGetSwapV2QuoteKlines (array_merge($request, $params));
        // var_dump ('lastCandleTs', strlen($response->data[$response->data) - 1] ? +new Date (strlen(+$response->data[$response->data) - 1].time) : 'none', strlen($response->data[$response->data) - 1] ? new Date (strlen(+$response->data[$response->data) - 1].time) : 'none');
        // var_dump ('response', $response);
        $ohlcvs = $this->safe_value($response, 'data', array());
        if (strlen($ohlcvs) > 0) {
            // BEGIN Patching last candle
            $lastRequest = $this->omit($request, array( 'startTime', 'endTime' ));
            $lastCandleResponse = $this->swap2OpenApiPublicGetSwapV2QuoteKlines (array_merge($lastRequest, $params));
            $lastOhlcv = $this->safe_value($lastCandleResponse, 'data', array());
            $lastOhlcvTime = $this->safe_integer($lastOhlcv, 'time');
            // var_dump('loht', $lastOhlcvTime, new Date ($lastOhlcvTime));
            $lastOhlcvFromArrayTime = $this->safe_integer(mb_substr($ohlcvs, -1), 'time');
            if ($lastOhlcvTime >= $lastOhlcvFromArrayTime) {
                $ohlcvs[] = $lastOhlcv;
            }
            // END Patching last candle
        }
        return $this->parse_ohlcvs($ohlcvs, $market, $timeframe, $since, $limit);
    }

    public function parse_ohlcvs($ohlcvs, $market = null, $timeframe = '1m', $since = null, $limit = null) {
        $results = array();
        for ($i = 0; $i < count($ohlcvs); $i++) {
            $results[] = $this->parse_ohlcv($ohlcvs[$i], $market);
        }
        $sorted = $this->sort_by($results, 0);
        $tail = ($since === null);
        return $this->filter_by_since_limit($sorted, $since, $limit, 0, $tail);
    }

    public function parse_ohlcv($ohlcv, $market = null) {
        return array(
            $this->safe_integer($ohlcv, 'time'), // timestamp
            $this->safe_number($ohlcv, 'open'), // open
            $this->safe_number($ohlcv, 'high'), // high
            $this->safe_number($ohlcv, 'low'), // low
            $this->safe_number($ohlcv, 'close'), // close
            $this->safe_number($ohlcv, 'volume'), // volume
        );
    }

    public function parse_order_status($status) {
        $statuses = array(
            'pending' => 'open',
            'new' => 'open',
            'partially_filled' => 'open',
            'filled' => 'closed',
            'canceled' => 'canceled',
            'pending_cancel' => 'canceling', // currently unused
            'rejected' => 'rejected',
            'expired' => 'expired',
        );
        return $this->safe_string($statuses, $status, $status);
    }

    public function parse_stop_trigger($status) {
        $statuses = array(
            'market_price' => 'mark', // unused
            'mark_price' => 'mark',
            'fill_price' => 'last', // unused
            'contract_price' => 'last',
            'index_price' => 'index', // unused
        );
        return $this->safe_string($statuses, $status, $status);
    }

    public function parse_order_type($type) {
        $types = array(
            'limit' => 'limit',
            'market' => 'market',
            'stop_market' => 'stop',
            'take_profit_market' => 'stop',
            'take_profit_limit' => 'stopLimit',
            'trigger_limit' => 'stopLimit',
            'trigger_market' => 'stop',
        );
        return $this->safe_string_lower($types, $type, $type);
    }

    public function parse_order($order, $market = null) {
        // {
        //     "code" => 0,
        //     "msg" => "",
        //     "data" => {
        //       "orders" => array(
        //         array(
        //           "symbol" => "BTC-USDT",
        //           "orderId" => 1651880171474731000,
        //           "side" => "SELL",
        //           "positionSide" => "LONG",
        //           "type" => "TAKE_PROFIT_MARKET",
        //           "origQty" => "0.0020",
        //           "price" => "0.0",
        //           "executedQty" => "0.0000",
        //           "avgPrice" => "0.0",
        //           "cumQuote" => "0",
        //           "stopPrice" => "35000.0",
        //           "profit" => "0.0",
        //           "commission" => "0.0",
        //           "status" => "NEW",
        //           "time" => 1682673897986,
        //           "updateTime" => 1682673897986
        //         ),
        //         array(
        //           "symbol" => "BTC-USDT",
        //           "orderId" => 1651880171445371000,
        //           "side" => "SELL",
        //           "positionSide" => "LONG",
        //           "type" => "STOP_MARKET",
        //           "origQty" => "0.0020",
        //           "price" => "0.0",
        //           "executedQty" => "0.0000",
        //           "avgPrice" => "28259.0",
        //           "cumQuote" => "0",
        //           "stopPrice" => "27000.0",
        //           "profit" => "0.0",
        //           "commission" => "0.0",
        //           "status" => "NEW",
        //           "time" => 1682673897979,
        //           "updateTime" => 1682673897979
        //         ),
        //         array(
        //           "symbol" => "BTC-USDT",
        //           "orderId" => 1651287406772699100,
        //           "side" => "BUY",
        //           "positionSide" => "LONG",
        //           "type" => "LIMIT",
        //           "origQty" => "0.0001",
        //           "price" => "25000.0",
        //           "executedQty" => "0.0000",
        //           "avgPrice" => "0.0",
        //           "cumQuote" => "0",
        //           "stopPrice" => "",
        //           "profit" => "0.0",
        //           "commission" => "0.0",
        //           "status" => "PENDING",
        //           "time" => 1682532572000,
        //           "updateTime" => 1682532571000
        //         ),
        //         {
        //           "symbol" => "BTC-USDT",
        //           "orderId" => 1651006482122227700,
        //           "side" => "BUY",
        //           "positionSide" => "LONG",
        //           "type" => "LIMIT",
        //           "origQty" => "0.0001",
        //           "price" => "25000.0",
        //           "executedQty" => "0.0000",
        //           "avgPrice" => "0.0",
        //           "cumQuote" => "0",
        //           "stopPrice" => "",
        //           "profit" => "0.0",
        //           "commission" => "0.0",
        //           "status" => "PENDING",
        //           "time" => 1682465594000,
        //           "updateTime" => 1682465594000
        //         }
        //       )
        //     }
        //   }
        $marketId = $this->safe_string($order, 'symbol');
        $market = $this->safe_market($marketId);
        $symbol = $market['symbol'];
        $id = $this->safe_string($order, 'orderId');
        $price = $this->safe_string($order, 'price');
        $amount = $this->safe_float($order, 'origQty');
        $filled = $this->safe_float($order, 'executedQty');
        $cost = $this->safe_string($order, 'executedQty');
        $average = $this->safe_string($order, 'avgPrice');
        $type = $this->parse_order_type($this->safe_string_lower($order, 'type'));
        $timestamp = $this->safe_integer($order, 'time');
        $rawStopTrigger = $this->safe_string_lower_2($order, 'trigger', 'workingType');
        $trigger = $this->parse_stop_trigger($rawStopTrigger);
        $side = $this->safe_string_lower($order, 'side');
        $positionSide = $this->safe_string_lower($order, 'positionSide');
        $reduceOnly = false;
        if ($side === 'buy') {
            if ($positionSide === 'long') {
                $reduceOnly = false;
            } else {
                $reduceOnly = true;
            }
        } else {
            if ($positionSide === 'long') {
                $reduceOnly = true;
            } else {
                $reduceOnly = false;
            }
        }
        $close = $reduceOnly;
        // $order $type LIMIT, MARKET, STOP_MARKET, TAKE_PROFIT_MARKET, TRIGGER_LIMIT, TRIGGER_MARKET
        // if ($rawStopTrigger) {
        //     if ($type === 'market') {
        //         $type = 'stop';
        //     } else {
        //         $type = 'stopLimit';
        //     }
        // } else {
        //     if ($type === 'market') {
        //         $type = 'market';
        //     } else {
        //         $type = 'limit';
        //     }
        // }
        $clientOrderId = $this->safe_string($order, 'orderId');
        $fee = $this->safe_string($order, 'comission');
        $rawStatus = $this->safe_string_lower($order, 'status');
        $status = $this->parse_order_status($rawStatus);
        $lastTradeTimestamp = $this->safe_integer($order, 'updateTime');
        $timeInForce = $this->safe_string($order, 'timeInForce');
        $postOnly = $timeInForce === 'PostOnly';
        $stopPrice = $this->safe_number($order, 'stopPrice');
        return $this->safe_order(array(
            'info' => $order,
            'id' => $id,
            'clientOrderId' => $clientOrderId,
            'timestamp' => $timestamp,
            'datetime' => $this->iso8601($timestamp),
            'lastTradeTimestamp' => $lastTradeTimestamp,
            'symbol' => $symbol,
            'type' => $type,
            'timeInForce' => 'GTC',
            'postOnly' => $postOnly,
            'side' => $side,
            'price' => $price,
            'stopPrice' => $stopPrice,
            'average' => $average,
            'cost' => $cost,
            'amount' => $amount,
            'filled' => $filled,
            'remaining' => null,
            'status' => $status,
            'fee' => $fee,
            'trades' => null,
            'reduceOnly' => $reduceOnly,  // TEALSTREET
            'close' => $close,  // TEALSTREET
            'trigger' => $trigger,  // TEALSTREET
        ), $market);
    }

    public function fetch_open_orders_v2($symbol = null, $since = null, $limit = null, $params = array ()) {
        /**
         * fetch all unfilled currently open $orders
         * @param {string|null} $symbol unified market $symbol
         * @param {int|null} $since the earliest time in ms to fetch open $orders for
         * @param {int|null} $limit the maximum number of  open $orders structures to retrieve
         * @param {array} $params extra parameters specific to the bybit api endpoint
         * @return {[array]} a list of ~@link https://docs.ccxt.com/#/?id=order-structure order structures~
         */
        $this->load_markets();
        $response = $this->swap2OpenApiPrivateGetSwapV2TradeOpenOrders ();
        $data = $this->safe_value($response, 'data', array());
        $orders = $this->safe_value($data, 'orders', array());
        $result = array();
        for ($i = 0; $i < count($orders); $i++) {
            $result[] = $this->parse_order($orders[$i]);
        }
        return $result;
    }

    public function fetch_orders($symbol = null, $since = null, $limit = null, $params = array ()) {
        return $this->fetch_open_orders_v2($symbol, $since, $limit, $params);
    }

    public function sign($path, $section = 'public', $method = 'GET', $params = array (), $headers = null, $body = null) {
        $type = $section[0];
        $version = $section[1];
        $access = $section[2];
        $rawPath = $path;
        $url = $this->implode_hostname($this->urls['api'][$type]);
        $url .= '/' . $version . '/' . $path;
        $path = $this->implode_params($path, $params);
        $params = $this->omit($params, $this->extract_params($path));
        $params = $this->keysort($params);
        if ($access === 'private') {
            $this->check_required_credentials();
            // positionSide is marked v1 :/
            $isOpenApi = mb_strpos($url, '/v2/') !== false || mb_strpos($url, 'positionSide/dual') !== false;
            $isUserDataStreamEp = mb_strpos($url, 'userDataStream') !== false;
            if ($isOpenApi || $isUserDataStreamEp) {
                $params = array_merge($params, array(
                    'timestamp' => $this->milliseconds() - 0,
                ));
                $params = $this->keysort($params);
                $paramString = $this->rawencode($params);
                $signature = $this->hmac($this->encode($paramString), $this->encode($this->secret), 'sha256');
                $params = array_merge($params, array(
                    'signature' => $signature,
                ));
                $headers = array(
                    'X-BX-APIKEY' => $this->apiKey,
                );
            } else {
                $params = array_merge($params, array(
                    'apiKey' => $this->apiKey,
                    'timestamp' => $this->milliseconds() - 0,
                ));
                $params = $this->keysort($params);
                // ACTUAL SIGNATURE GENERATION
                $paramString = $this->rawencode($params);
                $originString = $method . '/api/' . $version . '/' . $rawPath . $paramString;
                $signature = $this->hmac($this->encode($originString), $this->encode($this->secret), 'sha256', 'base64');
                // ACTUAL SIGNATURE GENERATION
                $params = array_merge($params, array(
                    'sign' => $signature,
                ));
            }
        }
        if ($params) {
            $url .= '?' . $this->urlencode($params);
        }
        return array( 'url' => $url, 'method' => $method, 'body' => $body, 'headers' => $headers );
    }

    public function handle_errors($httpCode, $reason, $url, $method, $headers, $body, $response, $requestHeaders, $requestBody) {
        if (!$response) {
            return; // fallback to default error handler
        }
        $errorCode = $this->safe_integer($response, 'code');
        // in theory 80012 is Service Unavailable, but returned on lev charges :/
        if ($errorCode !== null && $errorCode > 0 && $errorCode !== 80012) {
            throw new ExchangeError($this->id . ' ' . $this->json($response));
        }
    }
}
